In [1]:
import numpy as np

In [3]:
array1=np.array([ 
    [1,6,11],
    [2,7,12],
    [3,8,13],
    [4,9,14],
    [5,10,15],
                ])
array1

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [18]:
array1.shape

(5, 3)

In [5]:
array1[:,1]

array([ 6,  7,  8,  9, 10])

In [33]:
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [41]:
array2[4]=23
array2

array([15, 16, 17, 18, 23, 23, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [49]:
#np.flip(array2)
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 23, 23, 18, 17, 16, 15])

In [43]:
diagonal=array2 % 2 == 0
array2[diagonal]

array([16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50,
       52, 54])

In [44]:
valores=array2[diagonal][:5]
matriz_diag=np.diag(valores)
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 22,  0,  0],
       [ 0,  0,  0, 24,  0],
       [ 0,  0,  0,  0, 26]])

In [45]:
matriz_diag.ndim

2

In [57]:
matriz=np.random.random((5,3))
matriz

array([[0.87843367, 0.8657753 , 0.89339265],
       [0.30326319, 0.5640935 , 0.94048848],
       [0.74328054, 0.48595039, 0.43109473],
       [0.23485563, 0.60587528, 0.29912937],
       [0.32516509, 0.08913077, 0.45706651]])

In [58]:
matriz_diag @ matriz

array([[14.05493876, 13.85240483, 14.29428238],
       [ 5.45873734, 10.153683  , 16.92879264],
       [16.35217194, 10.69090856,  9.48408407],
       [ 5.63653511, 14.54100683,  7.17910491],
       [ 8.45429242,  2.31739993, 11.88372918]])